### PR TITLE
correction erreur BD

### PR DESCRIPTION
**Pull request by DSARRAZY**
Correction BDD : "auto_increment", rajout de champ "not null" a "null", rajout de données en dur.

### CODE REVIEW

**Review by RomainClair — CHANGES_REQUESTED** [review]
The sql file can't be imported if a previous version is already there.

You should update the readme to deal with both cases or better, have a sql import file that deal with this problem itself

**Comment by DSARRAZY** [comment]
Création automatique de la BDD "sharemybrain" et suppression si une BDD "sharemybrain" existe déjà sur le serveur + mise à jour du README : executer le scrip sql directement.

**Review by RomainClair — CHANGES_REQUESTED** [review]
After a second thought, it seems better not to force the db name.
So we'd better have a readme saying to to drop the database if it exists before importing, and a sql dump that doesn't choose the database name.

**Comment by DSARRAZY** [comment]
Correction done, BDD and README.

**Review by RomainClair — COMMENTED** [review]
The readme instructions could be more precise

**Review by RomainClair — APPROVED** [review]

**Pull request merged**
