### PR TITLE
Test responsive

### PR DESCRIPTION
**Pull request by mondini-max**
added to site the responsive design to page ; those are passed w**ithout errors errors by w3c validations for html and css**

### CODE REVIEW

**Review by RomainClair — CHANGES_REQUESTED** [review]
CSS indentation not consistent.
You should either minimize the CSS or let a readable CSS with a correct indentation. I suggest the later for now.

You should not use distant resources that you could have locally. Specially when the resource is on a no so interested in privacy tier like google. (The fonts)

You don't have any image URL linked in the theme table so it will be a problem to have theme image. Works only if the themes are static, so they don't need to bo in the database.

What's the purpose of this huge default block content in layout.html.twig ?
It seems to be code template that should be elsewhere. In the theme/index.html.twig for example.

**Comment by mondini-max** [comment]
# #1- **CSS indentation are corrected** ! 

1. Whitespace are removed 
2. Added comment to all section and part and make it hand able and readable css for every one 

# #2-Local font added to projet and its independeable from other! 
# #3-The URL are removed and placed by local photos and img but they are not placed in the databases ! 
# #4-he page has divided into diff parties and they are placed in bloc content .

**Review by RomainClair — CHANGES_REQUESTED** [review]
style.css has a error line 10 (a comma not needed) and coding style still not very good (indentation, space between selector and { etc...)

Some coding style (indentation) issues in styleresponsive.css too

Some files in the assets/fonts directory seems unnecessary (specimen files for example)

layout.html.twig doesn't have a block title anymore, so every pages are gonna bi named "ShareMyBrain - Accueil". It seems odd

Don't create a css twig block if you don't want the css to be overridden in extending template files.

Twig extends and block mecanism should probably be reviewed

**Comment by mondini-max** [comment]
Css line 10 has been corrected and divided into different parties css style of coding and indentation have been changed in the both css files!
the assets/fonts directory, that was  unnecessary files removed from the project.
the title of the layout has been removed and an undefined variable placed there.
the css block has been removed from the layout and index and replaced.
Twig extends and block mechanism has been reviewed again!

**Review by RomainClair — CHANGES_REQUESTED** [review]
style.css is invalid according to the w3c css validator.

Why is there a change in the composer.lock ?!?

Do you change versions or add new dependencies ?

**Pull request closed without merging**
