### PR TITLE
ShareMyBrain : first release

### PR DESCRIPTION
**Pull request by RomainClair**
You can list questions by theme, ask questions, answer questions and see the answers !

### CODE REVIEW

**Review by DSARRAZY — APPROVED** [review]
Ok très bon travail de l'équipe de Dev !

**Review by Frutios — APPROVED** [review]
It's a very good job !

**Review by louismarquenet — APPROVED** [review]
All good

**Review by mondini-max — APPROVED** [review]
vu et approuvé

**Pull request merged**
